### ISSUE TITLE
Why this app is installed, enter website is default to scholar?

### ISSUE THREAD

**Issue by 1a57danc3** [rexdf/Openshift-google-mirror#1]
How can i edit nginx.conf to enter google index page?

I try to edit /template/nginx.conf.erb

`set $upstream_host "scholar.google.com";` to `set $upstream_host "google.com";` .

It can redirect  to real `google.com` , But go to `xxx.rhcloud.com` .

Thank your answer.

**Comment by rexdf** [comment]
This repo is designed as a secondary reverse proxy for vps whose ip is blocked by google. So it does not substitute any content.

If you decide to use it directly on openshift, you need to deploy and then `git clone ssh://***`.
 Edit nginx.conf.erb and push it to openshift.

You maybe need url like `https://www.google.com/webhp?hl=en`, so just to visit `xxx.rhcloud.com/webhp?hl=en` to disable automatically redirecting.

Most of all, you need to stuggle to fight against js,css,html content substitutions.

It should be something like:

```
location / {
...
...
proxy_cookie_domain .google.com xxx.rhcloud.com;
subs_filter_types text/css text/xml text/javascript application/json;
subs_filter www.google.com  xxx.rhcloud.com;
# regex substitutions to block advertisement
subs_filter [0-9A-Za-z._-]*\\.doubleclick\\.net 127.0.0.1 igr; 
}
```

The above code is just to provide a idea about it. You need to figure out all the filters. However, google will update the main page to break your filters now and then. What's more, you maybe will have trouble in dealing with  authorization image, even on vps.

**Comment by 1a57danc3** [comment]
Thank you for your detailed answer!
